name: Django Docker Image
on:
  push:
    branches: main 

jobs:

  test:
    runs-on: ubuntu-latest  
    steps:
      - name: Get Code from Reposs
        uses: actions/checkout@v4
      - name: Check manage.py
        run: cat manage.py