name: Django Docker Image

on:
  push:
    branches: [ main ]

jobs:
 test:
        runs-on: ubuntu-latest    
        steps: 
         - name: Get Code from repo
           uses: actions/checkout@v4    
         - name: Find manage.py file
           run: cat manage.py
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get code from repo
    - uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build . --file Dockerfile --tag my-django-app:latest

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Push Docker Image
      run: docker push my-django-app:latest
      